import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Bell, Plus, Search, Settings } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Metadata } from "next";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";

export const metadata: Metadata = {
  title: "Dashboard | Sales Ninja",
  description: "Generated by create next app",
};
export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
        <div className="p-3 flex items-center justify-between bg-[#FFFFE4]">
          <div className="flex items-center gap-3 w-1/2">
            <SidebarTrigger className="bg-transparent border-none px-0" />
            <div className="flex items-center border-main gap-2 px-3 py-1 rounded w-full">
              <Search className="h-4 w-4" />
              <input
                type="text"
                placeholder="Search here"
                className="focus:outline-none border-none"
              />
            </div>
          </div>
          <div className="flex items-center gap-2 pr-5">
            <Popover>
              <PopoverTrigger>
                <div className="flex items-center gap-1 border rounded px-3 py-1 bg-sky-500 hover:bg-sky-600 cursor-pointer">
                  <Plus className="h-4 w-4" />
                  <span>ADD</span>
                </div>
              </PopoverTrigger>
              <PopoverContent>
                Place content for the popover here.
              </PopoverContent>
            </Popover>
            <Bell className="h-5 w-5" />
            <Settings className="h-5 w-5" />
            <div>
              <Popover>
                <PopoverTrigger>
                  <Avatar className="h-7 w-7">
                    <AvatarImage
                      src="https://github.com/shadcn.png"
                      alt="profile pic"
                    />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                </PopoverTrigger>
                <PopoverContent>
                  Place content for the popover here.
                </PopoverContent>
              </Popover>
            </div>
          </div>
        </div>
        <div className="">
          <div className="">{children}</div>
        </div>
      </main>
    </SidebarProvider>
  );
}
