import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard - Career Dock',
  description: 'Generated by Create Next App',
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div>header</div>
      <div>sidebar</div>
      <div>{children}</div>
    </div>
  );
}
