import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Providers from '@/lib/providers/Providers';
import { Toaster } from 'react-hot-toast';
import NextTopLoader from 'nextjs-toploader';
import { Suspense } from 'react';
import { GlobalLoading } from '@/components/global-loading';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Home - Career Dock',
  description: 'Generated by Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className=" bg-[#fafbfc]">
      <body className={poppins.className}>
        <Suspense fallback={<GlobalLoading />}>
          <NextTopLoader showSpinner={false} color="hsl(221.2 83.2% 53.3%)" />
          <Toaster />
          <Providers>{children}</Providers>
        </Suspense>
      </body>
    </html>
  );
}
