import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home - Career Dock",
  description: "Generated by Create Next App",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
