import Footer from '@/components/common/footer';
import Header from '@/components/common/header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Share',
  description: 'Generated by Create Next App',
};

export default function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className=" mt-12">{children}</div>;
}
